---    
roles:
  - name: geerlingguy.docker
    version: 7.8.0
collections:
  - name: community.docker
    version: 4.8.1
  - name: community.general
    version: 11.4.0
  - name: ansible.posix
    version: 2.1.0
